require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/campo_forms", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CampoForm. As you add validations to CampoForm, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CampoForm.create! valid_attributes
      get campo_forms_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      campo_form = CampoForm.create! valid_attributes
      get campo_form_url(campo_form)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_campo_form_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      campo_form = CampoForm.create! valid_attributes
      get edit_campo_form_url(campo_form)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CampoForm" do
        expect {
          post campo_forms_url, params: { campo_form: valid_attributes }
        }.to change(CampoForm, :count).by(1)
      end

      it "redirects to the created campo_form" do
        post campo_forms_url, params: { campo_form: valid_attributes }
        expect(response).to redirect_to(campo_form_url(CampoForm.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CampoForm" do
        expect {
          post campo_forms_url, params: { campo_form: invalid_attributes }
        }.to change(CampoForm, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post campo_forms_url, params: { campo_form: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested campo_form" do
        campo_form = CampoForm.create! valid_attributes
        patch campo_form_url(campo_form), params: { campo_form: new_attributes }
        campo_form.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the campo_form" do
        campo_form = CampoForm.create! valid_attributes
        patch campo_form_url(campo_form), params: { campo_form: new_attributes }
        campo_form.reload
        expect(response).to redirect_to(campo_form_url(campo_form))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        campo_form = CampoForm.create! valid_attributes
        patch campo_form_url(campo_form), params: { campo_form: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested campo_form" do
      campo_form = CampoForm.create! valid_attributes
      expect {
        delete campo_form_url(campo_form)
      }.to change(CampoForm, :count).by(-1)
    end

    it "redirects to the campo_forms list" do
      campo_form = CampoForm.create! valid_attributes
      delete campo_form_url(campo_form)
      expect(response).to redirect_to(campo_forms_url)
    end
  end
end
