require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/campos", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Campo. As you add validations to Campo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Campo.create! valid_attributes
      get campos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      campo = Campo.create! valid_attributes
      get campo_url(campo)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_campo_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      campo = Campo.create! valid_attributes
      get edit_campo_url(campo)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Campo" do
        expect {
          post campos_url, params: { campo: valid_attributes }
        }.to change(Campo, :count).by(1)
      end

      it "redirects to the created campo" do
        post campos_url, params: { campo: valid_attributes }
        expect(response).to redirect_to(campo_url(Campo.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Campo" do
        expect {
          post campos_url, params: { campo: invalid_attributes }
        }.to change(Campo, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post campos_url, params: { campo: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested campo" do
        campo = Campo.create! valid_attributes
        patch campo_url(campo), params: { campo: new_attributes }
        campo.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the campo" do
        campo = Campo.create! valid_attributes
        patch campo_url(campo), params: { campo: new_attributes }
        campo.reload
        expect(response).to redirect_to(campo_url(campo))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        campo = Campo.create! valid_attributes
        patch campo_url(campo), params: { campo: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested campo" do
      campo = Campo.create! valid_attributes
      expect {
        delete campo_url(campo)
      }.to change(Campo, :count).by(-1)
    end

    it "redirects to the campos list" do
      campo = Campo.create! valid_attributes
      delete campo_url(campo)
      expect(response).to redirect_to(campos_url)
    end
  end
end
