require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/docentes", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Docente. As you add validations to Docente, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Docente.create! valid_attributes
      get docentes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      docente = Docente.create! valid_attributes
      get docente_url(docente)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_docente_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      docente = Docente.create! valid_attributes
      get edit_docente_url(docente)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Docente" do
        expect {
          post docentes_url, params: { docente: valid_attributes }
        }.to change(Docente, :count).by(1)
      end

      it "redirects to the created docente" do
        post docentes_url, params: { docente: valid_attributes }
        expect(response).to redirect_to(docente_url(Docente.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Docente" do
        expect {
          post docentes_url, params: { docente: invalid_attributes }
        }.to change(Docente, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post docentes_url, params: { docente: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested docente" do
        docente = Docente.create! valid_attributes
        patch docente_url(docente), params: { docente: new_attributes }
        docente.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the docente" do
        docente = Docente.create! valid_attributes
        patch docente_url(docente), params: { docente: new_attributes }
        docente.reload
        expect(response).to redirect_to(docente_url(docente))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        docente = Docente.create! valid_attributes
        patch docente_url(docente), params: { docente: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested docente" do
      docente = Docente.create! valid_attributes
      expect {
        delete docente_url(docente)
      }.to change(Docente, :count).by(-1)
    end

    it "redirects to the docentes list" do
      docente = Docente.create! valid_attributes
      delete docente_url(docente)
      expect(response).to redirect_to(docentes_url)
    end
  end
end
