require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/elementos", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Elemento. As you add validations to Elemento, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Elemento.create! valid_attributes
      get elementos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      elemento = Elemento.create! valid_attributes
      get elemento_url(elemento)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_elemento_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      elemento = Elemento.create! valid_attributes
      get edit_elemento_url(elemento)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Elemento" do
        expect {
          post elementos_url, params: { elemento: valid_attributes }
        }.to change(Elemento, :count).by(1)
      end

      it "redirects to the created elemento" do
        post elementos_url, params: { elemento: valid_attributes }
        expect(response).to redirect_to(elemento_url(Elemento.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Elemento" do
        expect {
          post elementos_url, params: { elemento: invalid_attributes }
        }.to change(Elemento, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post elementos_url, params: { elemento: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested elemento" do
        elemento = Elemento.create! valid_attributes
        patch elemento_url(elemento), params: { elemento: new_attributes }
        elemento.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the elemento" do
        elemento = Elemento.create! valid_attributes
        patch elemento_url(elemento), params: { elemento: new_attributes }
        elemento.reload
        expect(response).to redirect_to(elemento_url(elemento))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        elemento = Elemento.create! valid_attributes
        patch elemento_url(elemento), params: { elemento: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested elemento" do
      elemento = Elemento.create! valid_attributes
      expect {
        delete elemento_url(elemento)
      }.to change(Elemento, :count).by(-1)
    end

    it "redirects to the elementos list" do
      elemento = Elemento.create! valid_attributes
      delete elemento_url(elemento)
      expect(response).to redirect_to(elementos_url)
    end
  end
end
