require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/elemento_forms", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ElementoForm. As you add validations to ElementoForm, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ElementoForm.create! valid_attributes
      get elemento_forms_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      elemento_form = ElementoForm.create! valid_attributes
      get elemento_form_url(elemento_form)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_elemento_form_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      elemento_form = ElementoForm.create! valid_attributes
      get edit_elemento_form_url(elemento_form)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ElementoForm" do
        expect {
          post elemento_forms_url, params: { elemento_form: valid_attributes }
        }.to change(ElementoForm, :count).by(1)
      end

      it "redirects to the created elemento_form" do
        post elemento_forms_url, params: { elemento_form: valid_attributes }
        expect(response).to redirect_to(elemento_form_url(ElementoForm.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ElementoForm" do
        expect {
          post elemento_forms_url, params: { elemento_form: invalid_attributes }
        }.to change(ElementoForm, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post elemento_forms_url, params: { elemento_form: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested elemento_form" do
        elemento_form = ElementoForm.create! valid_attributes
        patch elemento_form_url(elemento_form), params: { elemento_form: new_attributes }
        elemento_form.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the elemento_form" do
        elemento_form = ElementoForm.create! valid_attributes
        patch elemento_form_url(elemento_form), params: { elemento_form: new_attributes }
        elemento_form.reload
        expect(response).to redirect_to(elemento_form_url(elemento_form))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        elemento_form = ElementoForm.create! valid_attributes
        patch elemento_form_url(elemento_form), params: { elemento_form: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested elemento_form" do
      elemento_form = ElementoForm.create! valid_attributes
      expect {
        delete elemento_form_url(elemento_form)
      }.to change(ElementoForm, :count).by(-1)
    end

    it "redirects to the elemento_forms list" do
      elemento_form = ElementoForm.create! valid_attributes
      delete elemento_form_url(elemento_form)
      expect(response).to redirect_to(elemento_forms_url)
    end
  end
end
